Implement cookie for theme choice
DavidMatalik/portfolio pull request #12
Opened 2021-06-25 13:00 UTC by DavidMatalik

![Peek 2021-06-25 14-59](https://user-images.githubusercontent.com/11299099/123428389-0e97c380-d5c6-11eb-957d-aa28ce7836a8.gif)

2021-06-27 07:04 UTC, RichStone requested changes
where did you copy-paste get- and setCookie from? :D (I don't like how they named things, it makes the boiler code way less readable. It's now part of your codebase, so I'd change the namings ;))

getCookie and setCookie functions are great candidates for `lib`-like functionality. (functionality that doesn't belong to any component really and that's potentially reusable across the applicaiton)
wanna try to add a `src/lib` folder to your application and extract these functions there?

2021-06-27 07:09 UTC, RichStone commented on src/App.js
> +      mode: (this.getCookie('mode') === 'true') ? true : false
would this be enough? 
```js
mode: this.getCookie('mode') === 'true'
```

2021-06-27 10:57 UTC, DavidMatalik commented
> where did you copy-paste get- and setCookie from? :D (I don't like how they named things, it makes the boiler code way less readable. It's now part of your codebase, so I'd change the namings ;))
> 
> getCookie and setCookie functions are great candidates for `lib`-like functionality. (functionality that doesn't belong to any component really and that's potentially reusable across the applicaiton)
> wanna try to add a `src/lib` folder to your application and extract these functions there?

Yeaaaahh I forgot about it... You've mentioned it already. ;) And yes it felt a bit wrong to put it there. I will change it as requested.

2021-06-27 10:59 UTC, DavidMatalik commented
> where did you copy-paste get- and setCookie from? :D (I don't like how they named things, it makes the boiler code way less readable. It's now part of your codebase, so I'd change the namings ;))

From w3schools. ;) I'll change the naming.

2021-06-27 11:03 UTC, DavidMatalik commented on src/App.js
> +      mode: (this.getCookie('mode') === 'true') ? true : false
Ah yes, you are right =)

2021-06-30 21:26 UTC, RichStone approved these changes

2021-06-30 21:26 UTC, RichStone commented
coool!

2021-07-08 15:11 UTC, merged